invoices/index.html

Business.Country was not working:
This fixes it. 
Tested locally:

Fix `business.Country` in invoice html

---

.github/workflows/release.yml
_build/publish.js
actionbutton/package.json
clipboard/package.json
exoplanet/package.json
inspect/package.json
invoices/package.json
map/package.json
markdown/package.json
pedigree/package.json
printlabels/package.json
purchase-orders/package.json
renderhtml/package.json
viewer/package.json

Configuring repository as a Grist Custom Widget Repository source. Each custom widget folder was converted to a simple npm package. On every commit to master, GitHub action will create an automatic release with a single manifest file that lists all available (and published widgets) and can be used as a source of all custom widgets available in Grist. 
- Converting folders to simple npm packages
- Adding GitHub action to build manifest file for Grist.

Exposing custom widgets in Grist

---

renderhtml/index.html

These will allow the specified tags/attributes pass sanitization.
Also, if scripts are allowed, allow them to be executed.
This allows preparing more interesting HTML to render using the renderhtml widget, including things like embedding third-party sites, e.g. twitter timelines.

Support URL params 'tags' (e.g. 'iframe,script') and 'attr'

---

actionbutton/package.json
clipboard/package.json
exoplanet/package.json
inspect/package.json
invoices/package.json
map/package.json
markdown/package.json
pedigree/package.json
printlabels/package.json
purchase-orders/package.json
renderhtml/package.json
viewer/package.json

Updating widget desired access levels.
Each widget has an additional option, `accessLevel`, which Grist uses to prompt the user for permission approval.

Updating widgets access levels.

---

inspect/index.html

Inspect widget's landing page had a broken link to the onOptions widget.

Broken link in inspect widget landing page.

---

actionbutton/actionbutton.js
actionbutton/package.json
clipboard/index.html
clipboard/package.json
inspect/columns.html
inspect/index.html
inspect/package.json
map/package.json
map/page.js
markdown/index.html
printlabels/package.json
printlabels/printlabels.js
renderhtml/index.html
renderhtml/package.json
viewer/index.html
viewer/package.json

All exposed custom widgets are not updated to use the new column API.
Change is backward compatible - each widget can still work without any mappings set.

Using columns mapping API in exposed widgets.

---

map/index.html
map/package.json
map/page.js
map/screen.css

Currently, there are two versions of Map widget: Map and Location. The only difference was the initial mode set by the query parameter. This PR removes the Location widget and adds an option menu (available under "Open Configuration" button) to change the mode within the widget.
The query parameter is still respected (as a default mode), and the Location widget will still be visible for documents that use it, so there shouldn't be any breaking changes here.

Removing Location widget. Adding options to Map widget.

---

map/index.html
map/page.js

When the map is showing many locations, the selected location can be lost through clustering as the user zooms in. This adds a hacky way to keep that location open.

Map: keep popup open on zoom

---

invoices/invoice.js

This tweaks the invoice custom widget to use Deduction and Taxes columns when the Subtotal is automatically computed. See https://github.com/gristlabs/grist-core/issues/189

allow Deduction and Taxes with auto-Subtotal

---

dropbox-embed/index.html
dropbox-embed/index.js
dropbox-embed/package.json

Use can place [shared links](https://help.dropbox.com/files-folders/share/view-only-access) to Dropbox files or folders into a cell, and the widget will show a preview. For example:

Add Dropbox Embedder custom widget 

---

markdown/index.html

Markdown widget was stealing focus from Grist when the user switched between filled and empty rows.
This change is addressing this issue https://community.getgrist.com/t/issue-markdown-widget-stealing-focus/1450.

Keeping focus within Grist document when switching to an empty editor.

---

markdown/index.html
markdown/index.js

- JS code moved from index.html into a separate JS file
- Styling updated to look cleaner (more like Github's markdown styling) rather than default styles.
- Toolbar only shown in full in edit mode
- In read mode only the "edit" button is overlaid on the content, for clean rendering; and hidden when printing.
- Key behavior unchanged (Enter or Space to start editing, Cmd-S or Escape to stop)
Some previews:
Before
After

Improvements to the markdown widget

---

flashcards/index.js

By showing the list index to the user, for a quiz with 10 questions, the progress bar starts at "0 of 10" and the last card shows "9 of 10", so it seems like you never get to the final card.
This changes it to start at "1 of 10" and end on "10 of 10".

show progress from "1 to N" instead of "0 to N"

---

flashcards/index.js

The previous PR fixed the text to go from 1-N instead of 0-N.
This PR fixes the progress bar so that when you're on the final card, it is 100% full.
Sorry I didn't catch it in the previous PR!

show progress bar as full when on last card

---

notepad/index.css

The notepad widget with the Quill editor didn't support printing styles. This adds some basic support that should work in most cases.

Updating css for printing in notepad widget

---

notepad/index.css
notepad/index.html
notepad/index.js

The default Quill theme's toolbar takes up a lot of space, so I wanted to allow selecting a different theme. The Bubble theme only shows the toolbar as a tooltip when text is selected. This PR adds a config screen where the theme can be changed.
As a side-note: this method of setting widget options seems rather clunky. Has there been any discussion about having widgets expose options directly in the sidebar?

Enable theme configuration for Notepad widget

---

.github/workflows/release.yml

It would be useful to have a copy of `manifest.json` that is usable from browsers (for grist-static). GitHub doesn't set a CORS origin wildcard for releases, but it does for GitHub Pages. Also jsdelivr can mirror branches (but not releases). So this adds a build step to make a branch that contains `master` plus the generated `manifest.json` file.

make manifest.json available for use from browsers

---

memes/index.html
memes/script.js
memes/style.css

This adds in a custom widget that was lying around in my personal fork, and got used to support a Grist template:
https://templates.getgrist.com/gtzQwTXkgzFG/Meme-Generator
It isn't great code but it works, so just adding it unchanged other than some comments and formatting. I occasionally zap my personal fork so it would be safer not to rely on it.

add custom widget supporting memes template

---

.gitignore
notepad/index.css
notepad/index.html
notepad/index.js

The notepad widget was showing an unneeded scrollbar.
Additionally, added a `new` record handler, which clears and disables the editor.

Removing scrollbar, handling new record

---

calendar/page.js

- clicking or creating an event now moves focus to the widget
- new events can no longer be created if the widget isn't configured
- isAllDay can be set even when there is no endDate
- events that start and end at 12:00am are now visible in all views
- an invalid or missing endDate is now handled by using one that is 30 minutes after startDate

Polish calendar widget

---

map/page.js
markdown/index.js

Handling `onNewRecord` in map and markdown widget.

Adding support for new record event for map and markdown widget

---

calendar/page.js
test/calendar.ts
test/declarations.d.ts
test/getGrist.ts
test/gristWebDriverUtils.ts

Checking if widget has write access. If not, disabling the calendar edit actions.
Ignoring errors from ACL, so that the days are not selected unnecessary.

Calendar read access

---

calendar/page.js
package.json
test/calendar.ts
test/gristWebDriverUtils.ts

Using new `setCursor` API in the calendar widget, which will allow bi-directional linking to work.
New test was added and some updated.
https://github.com/gristlabs/grist-widget/pull/73

[Calendar] Adding support for bi-directional linking

---

calendar/page.js

This line was not needed after all.
And since those methods are async, it is possible to click very fast to make an infinity loop.

[Calendar] Removing redundant cursor position call

---

calendar/page.js

Adding strict type checking for dates and toggles. As those columns can't be inferred by Grist

Adding strict type checking for dates and toggles

---

.gitignore
buildtools/bundle.js
buildtools/publish.js
calendar/package.json
package.json

It can be useful to include custom widgets with Grist, so they can be used offline, or for simpler archiving, or for tighter integration with the rest of the app. This PR includes a script for collecting custom widget files in a structured bundle. It is parallel work to developments in grist-core, including https://github.com/gristlabs/grist-core/pull/714

support for creating widget bundles

---

buildtools/bundle.js
package.json
test/flashcards.ts
test/inspect.ts
yarn.lock

This adds a few more flags to the bundling script, and then uses them in a `prepare` script to assemble a bundle for insertion into grist-core. The bundle can be previewed as a tarball with:
```
yarn pack
```
or published to the npm registry as [@gristlabs/grist-widget](https://www.npmjs.com/package/@gristlabs/grist-widget) with:
```
yarn publish --access public
```
There will be a companion PR to grist-core to make use of the package.

create a widget bundle for insertion into grist-core via npm packaging

---

test/calendar.ts

There is an extra section due to the new Record Card feature, so ids have changed. (thanks for tip @georgegevoian)

update Calendar test

---

calendar/page.js
test/calendar.ts

New test will fail temporarily until the Grist image is updated with support for opening a Record Card from a custom widget.

Open Record Card on Calendar event click

---

actionbutton/actionbutton.css
actionbutton/actionbutton.js
actionbutton/index.html

Original idea of @emanuelegissi
If, instead of a dictionary, a list of dictionaries is defined, several buttons will be displayed.
This is backward-compatible: if only one dictionary is defined, it will work as before (except for styling changes).
See in action here: https://docs.getgrist.com/dd1Amj8bbHzK/Tests/p/23#a1.s135.r1.c219.

Allow several action buttons

---

map/index.html
map/page.js
map/screen.css

To make it easier to change map source. For example, (and to test), those values work:
```
https://tile.openstreetmap.org/{z}/{x}/{y}.png
&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>
```

Make map source configurable

---

notepad/index.html
notepad/index.js

Hi,
My attempt to fix #128 .
Working deployment on https://guillett.github.io/grist-widget/ (notepad only)

Add optional HTML export to Notepad widget

---

calendar/package.json

The calendar widget currently doesn't work in Grist Desktop, due to it trying to fetch certain dependencies from the internet.
This PR adds those dependencies to the bundle, enabling offline use.
This change was tested locally by producing a new bundle and rebuilding Grist Desktop.

Fixes Calendar not working offline

---

custom-widget-builder/api.js
custom-widget-builder/index.html

When an inner widget was reporting some mandatory columns to map, the builder was causing infinite loop. More in comment, but here is summary.
- Builder was sending ready message to Grist, without any mapped columns
- Grist was rendering the widget, sending JS/HTML back
- Builder was creating inner widget, which called ready method and reported some mandatory columns to map
- Grist unloads builder, as columns where not mapped
- User mapped a column
- Grist loads builder
- Builder reports back to Grist that no columns to map (and no mandatory columns anymore). 
- Grist unloads builder once again (as mandatory option has changed, and Grist is sensitive here).
- Grist sees no mandatory columns, so shows builder once again.
- Builder, reports back no mandatory columns, creates inner widget, …

editor: Fixing bug that caused infinite loop during preview

---

map/page.js

As index.html is using the latest version of leaflet-control-geocoder and the API changed in 3.0.0 with this example:
```diff
Migrate from callbacks to Promise
-geocoder.geocode(query, callback);
+geocoder.geocode(query).then(callback);
-geocoder.reverse(latlng, scale, callback);
+geocoder.reverse(latlng, scale).then(callback);
Migrate from callbacks to async-await
-geocoder.geocode(query, callback);
+const results = await geocoder.geocode(query);
-geocoder.reverse(latlng, scale, callback);
+const results = await geocoder.reverse(latlng, scale);
```
The usage in the map widget also needs updating to correspond.

Fix geocoder to new 3.x API

---

calendar/index.html
calendar/package.json
map/index.html
markdown/index.html
notepad/index.html
stock-monitor/index.html

Due to the recent somewhat common unavailability of unpkg.com ( https://github.com/unpkg/unpkg/issues/443 ) I have implemented a move of all the references from unpkg.com to cdn.jsdelivr.net . cdn.jsdeli.net has already been used for most of the CDN calls before, this just cleans things up and moves everything to one single provider. The files linked are identical.

Move from unkpg.com to cdn.jsdelivr.net

---

calendar/page.js

Fix wrong time displayed due to incorrect DST correction done when document and date timezones are the same

Fix wrong time displayed in Calendar widget

---

test/app/README.md
test/app/client/components/commandList.ts
test/app/common/DocActions.ts
test/calendar.ts
test/getGrist.ts
test/gristWebDriverUtils.ts
test/tsconfig.json
test/viewer.ts

As the header of that file says, it should have never been independently changed. Lots of changes happened to it regardless since the file was copied.
As a first step to fixing the tests, this restores the original copy from grist-core and moves all of the additions to a supplemental subclass.

tests: restore gristWebDriverUtils from grist-core
